### ISSUE TITLE
Can't embed pdf in self contained html

### ISSUE THREAD

**Issue by MislavSag** [jmgirard/embedpdf#4]
Hi,

I am trying to embed pdf in my quartro document:

```
{{< pdf C:/Users/Mislav/Documents/GitHub/SNPectinatusAlgos/LeastVolatile/e46cbca50fbc0d919dcf59dc49b28b89.pdf width=100% height=800 >}}
```
But  it just show above code in my quartro document, it doesn't embed pdf.

Here is header I usein the document

---
title: "Least volatile"
date: "`r format(Sys.Date(), '%d-%m-%Y')`"
format: 
  html:
    theme: "cosmo"
    highlight-style: "github"
    toc: true
    toc-depth: 2
    self-contained: true
---
Maybe there is a problem because the html document is set to self contained.

**Comment by jmgirard** [comment]
So it will work if you keep/send the pdf file with the html file (as a separate file but in the same folder), but it apparently can't store a PDF file within a self-contained HTML file itself.

```md
---
title: "Embed test"
format: html
embed-resources: true
---

{{< pdf dummy.pdf width=600 >}}
```

**Comment by jmgirard** [comment]
See my quarto post here for progress on getting this feature enabled:
https://github.com/quarto-dev/quarto-cli/discussions/10177

**Comment by jmgirard** [comment]
Ok, apparently, it works if you do

```md
---
title: "Embed test"
format: html
embed-resources: true
---

![](dummy.pdf){width=100% height=800}
```

**Comment by MislavSag** [comment]
Still doesn't work for me. Her eis my qmd file

```
---
title: "Least volatile"
date: "`r format(Sys.Date(), '%d-%m-%Y')`"
format: 
  html:
    theme: "cosmo"
    highlight-style: "github"
    toc: true
    toc-depth: 2
    # self-contained: true
embed-resources: true
---

![](C:/Users/Mislav/Documents/GitHub/SNPectinatusAlgos/LeastVolatile/4384d335daa51ba158bb086c909d50fc.pdf){width=100% height=800}
```
